// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contracts/proto/notification/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessingCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingCompletedRequest) Reset() {
	*x = ProcessingCompletedRequest{}
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingCompletedRequest) ProtoMessage() {}

func (x *ProcessingCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingCompletedRequest.ProtoReflect.Descriptor instead.
func (*ProcessingCompletedRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingCompletedRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ProcessingCompletedRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProcessingCompletedRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProcessingCompletedRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProcessingCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingCompletedResponse) Reset() {
	*x = ProcessingCompletedResponse{}
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingCompletedResponse) ProtoMessage() {}

func (x *ProcessingCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingCompletedResponse.ProtoReflect.Descriptor instead.
func (*ProcessingCompletedResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessingCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessingCompletedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contracts_proto_notification_notification_proto protoreflect.FileDescriptor

const file_contracts_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	"/contracts/proto/notification/notification.proto\x12\fnotification\"V\n" +
	"\x10SendEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"G\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\x1aProcessingCompletedRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"Q\n" +
	"\x1bProcessingCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd3\x01\n" +
	"\x13NotificationService\x12L\n" +
	"\tSendEmail\x12\x1e.notification.SendEmailRequest\x1a\x1f.notification.SendEmailResponse\x12n\n" +
	"\x17SendProcessingCompleted\x12(.notification.ProcessingCompletedRequest\x1a).notification.ProcessingCompletedResponseB_Z]github.com/alimarzban99/video-processing-platform/contracts/proto/notification;notificationpbb\x06proto3"

var (
	file_contracts_proto_notification_notification_proto_rawDescOnce sync.Once
	file_contracts_proto_notification_notification_proto_rawDescData []byte
)

func file_contracts_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_contracts_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_contracts_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_notification_notification_proto_rawDesc), len(file_contracts_proto_notification_notification_proto_rawDesc)))
	})
	return file_contracts_proto_notification_notification_proto_rawDescData
}

var file_contracts_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contracts_proto_notification_notification_proto_goTypes = []any{
	(*SendEmailRequest)(nil),            // 0: notification.SendEmailRequest
	(*SendEmailResponse)(nil),           // 1: notification.SendEmailResponse
	(*ProcessingCompletedRequest)(nil),  // 2: notification.ProcessingCompletedRequest
	(*ProcessingCompletedResponse)(nil), // 3: notification.ProcessingCompletedResponse
}
var file_contracts_proto_notification_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.SendEmail:input_type -> notification.SendEmailRequest
	2, // 1: notification.NotificationService.SendProcessingCompleted:input_type -> notification.ProcessingCompletedRequest
	1, // 2: notification.NotificationService.SendEmail:output_type -> notification.SendEmailResponse
	3, // 3: notification.NotificationService.SendProcessingCompleted:output_type -> notification.ProcessingCompletedResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_proto_notification_notification_proto_init() }
func file_contracts_proto_notification_notification_proto_init() {
	if File_contracts_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_notification_notification_proto_rawDesc), len(file_contracts_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_contracts_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_contracts_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_contracts_proto_notification_notification_proto = out.File
	file_contracts_proto_notification_notification_proto_goTypes = nil
	file_contracts_proto_notification_notification_proto_depIdxs = nil
}
